# Generated by Django 2.2.15 on 2020-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage", name="body", field=models.TextField(blank=True),
        ),
    ]
