# Generated by Django 2.2.15 on 2020-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200819_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='nghgjgjhg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='tyrytrtyrtyrtr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
