# Generated by Django 2.2.15 on 2020-08-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200819_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='nghgjgjhg',
        ),
    ]
