# Generated by Django 2.2.15 on 2020-08-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_customtext_nghgjgjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='tyrytrtyrtyrtr',
        ),
    ]
